name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the tests container using cache
        uses: whoan/docker-build-with-cache-action@tag-image-as-a-separate-step
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: jstockwin/arrow-voting-test
          image_tag: test
          dockerfile: dockerfiles/Dockerfile_tests
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run linting
        run: docker run --rm jstockwin/arrow-voting-test:test .github/scripts/lint.sh
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: docker run --rm jstockwin/arrow-voting-test:test .github/scripts/test.sh
